export const countries = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antigua & Barbuda',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia',
  'Bosnia & Herzegovina',
  'Botswana',
  'Brazil',
  'British Virgin Islands',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cape Verde',
  'Cayman Islands',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Congo',
  'Cook Islands',
  'Costa Rica',
  'Cote D Ivoire',
  'Croatia',
  'Cruise Ship',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'England',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Falkland Islands',
  'Faroe Islands',
  'Fiji',
  'Finland',
  'France',
  'French Polynesia',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guam',
  'Guatemala',
  'Guernsey',
  'Guinea',
  'Guinea Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Isle of Man',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jersey',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macau',
  'Macedonia',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Namibia',
  'Nepal',
  'Netherlands',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Northern Ireland',
  'Norway',
  'Oman',
  'Pakistan',
  'Palestine',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Reunion',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Pierre & Miquelon',
  'Samoa',
  'San Marino',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'South Africa',
  'South Korea',
  'Spain',
  'Sri Lanka',
  'Saint Kitts & Nevis',
  'Saint Lucia',
  'Saint Vincent',
  'Scotland',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  "Timor L'Este",
  'Togo',
  'Tonga',
  'Trinidad & Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks & Caicos',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States of America',
  'Uruguay',
  'Uzbekistan',
  'Wales',
  'Vanuatu',
  'Venezuela',
  'Vietnam',
  'Virgin Islands (US)',
  'Yemen',
  'Zambia',
  'Zimbabwe',
] as const;

export const games = ['Assetto Corsa Competizione', 'F1 23'] as const;

export const eventTypes = ['single', 'championship'] as const;

export const sessionTypes = [
  'briefing',
  'practice',
  'qualifying',
  'race',
] as const;

export const cars = {
  'Assetto Corsa Competizione': [
    { name: 'Aston Martin V12', type: 'GT3' },
    { name: 'Aston Martin V8', type: 'GT3' },
    { name: 'Audi R8 LMS', type: 'GT3' },
    { name: 'Audi R8 LMS EVO', type: 'GT3' },
    { name: 'Audi R8 LMS EVO II', type: 'GT3' },
    { name: 'Bentley Continental 2015', type: 'GT3' },
    { name: 'Bentley Continental 2018', type: 'GT3' },
    { name: 'BMW M6', type: 'GT3' },
    { name: 'BMW M4', type: 'GT3' },
    { name: 'Jaguar G3', type: 'GT3' },
    { name: 'Ferrari 296', type: 'GT3' },
    { name: 'Ferrari 488', type: 'GT3' },
    { name: 'Ferrari 488 EVO', type: 'GT3' },
    { name: 'Honda NSX', type: 'GT3' },
    { name: 'Honda NSX Evo', type: 'GT3' },
    { name: 'Lamborghini Huracán', type: 'GT3' },
    { name: 'Lamborghini Huracán Evo', type: 'GT3' },
    { name: 'Lamborghini Huracán Evo2', type: 'GT3' },
    { name: 'Lexus RC F', type: 'GT3' },
    { name: 'McLaren 650S', type: 'GT3' },
    { name: 'McLaren 720S', type: 'GT3' },
    { name: 'McLaren 720S Evo', type: 'GT3' },
    { name: 'Mercedes AMG', type: 'GT3' },
    { name: 'Mercedes AMG EVO', type: 'GT3' },
    { name: 'Nissan GTR NISMO 2015', type: 'GT3' },
    { name: 'Nissan GTR NISMO 2018', type: 'GT3' },
    { name: 'Porsche 911 GT3R', type: 'GT3' },
    { name: 'Porsche 911 II GT3R', type: 'GT3' },
    { name: 'Porsche 911 GT3 R (992)', type: 'GT3' },
    { name: 'Reiter Engineering R-EX', type: 'GT3' },
    { name: 'Alpine A110 GT4', type: 'GT4' },
    { name: 'AMR V8 VANTAGE GT4', type: 'GT4' },
    { name: 'Audi R8 LMS GT4', type: 'GT4' },
    { name: 'BMW M4 GT4', type: 'GT4' },
    { name: 'Chevrolet Camaro R GT4', type: 'GT4' },
    { name: 'Ginetta G55 GT4', type: 'GT4' },
    { name: 'KTM X-BOW GT4', type: 'GT4' },
    { name: 'Maserati Granturismo MC GT4', type: 'GT4' },
    { name: 'McLaren 570S GT4', type: 'GT4' },
    { name: 'Mercedes AMG GT4', type: 'GT4' },
    { name: 'Porsche 718 Cayman GT4 Clubsport', type: 'GT4' },
    { name: 'Lamborghini Huracán Super Trofeo', type: 'GTC' },
    { name: 'Lamborghini Huracán Super Trofeo EVO2', type: 'GTC' },
    { name: 'Porsche 911 II GT3 Cup', type: 'GTC' },
    { name: 'Porsche 911 GT3 Cup (992)', type: 'GTC' },
    { name: 'Ferrari 488 Challenge Evo', type: 'GTC' },
    { name: 'BMW M2 CS Racing', type: 'TCX' },
  ],
  'F1 23': [],
} as const satisfies Record<
  (typeof games)[number],
  Readonly<Array<{ name: string; type: string }>>
>;

export const tracks = {
  'Assetto Corsa Competizione': [
    { name: 'Barcelona', country: 'Spain' },
    { name: 'Bathurst Mount Panorama', country: 'Australia' },
    { name: 'Brands Hatch', country: 'United Kingdom' },
    { name: 'Circuit of the Americas', country: 'United States of America' },
    { name: 'Donington Park', country: 'United Kingdom' },
    { name: 'Hungaroring', country: 'Hungary' },
    { name: 'Imola', country: 'Italy' },
    { name: 'Indianapolis', country: 'United States of America' },
    { name: 'Kyalami', country: 'South Africa' },
    { name: 'Laguna Seca', country: 'United States of America' },
    { name: 'Misano', country: 'Italy' },
    { name: 'Monza', country: 'Italy' },
    { name: 'Nürburgring', country: 'Germany' },
    { name: 'Oulton Park', country: 'United Kingdom' },
    { name: 'Paul Ricard', country: 'France' },
    { name: 'Silverstone', country: 'United Kingdom' },
    { name: 'Snetterton', country: 'United Kingdom' },
    { name: 'Spa-Francorchamps', country: 'Belgium' },
    { name: 'Suzuka', country: 'Japan' },
    { name: 'Valencia', country: 'Spain' },
    { name: 'Watkins Glen', country: 'United States of America' },
    { name: 'Zandvoort', country: 'Netherlands' },
    { name: 'Zolder', country: 'Belgium' },
  ],
  'F1 23': [
    { name: 'Albert Park', country: 'Australia' },
    { name: 'Autódromo Hermanos Rodríguez', country: 'Mexico' },
    { name: 'Autódromo José Carlos Pace', country: 'Brazil' },
    { name: 'Bahrain International Circuit', country: 'Bahrain' },
    { name: 'Baku City Circuit', country: 'Azerbaijan' },
    { name: 'Barcelona', country: 'Spain' },
    { name: 'Circuit Gilles Villenueve', country: 'Canada' },
    { name: 'Circuit of the Americas', country: 'United States of America' },
    { name: 'Hungaroring', country: 'Hungary' },
    { name: 'Imola', country: 'Italy' },
    { name: 'Jeddah Corniche Circuit', country: 'Saudi Arabia' },
    {
      name: 'Las Vegas Strip Street Circuit',
      country: 'United States of America',
    },
    { name: 'Losail International Circuit', country: 'Qatar' },
    {
      name: 'Miami International Autodrome',
      country: 'United States of America',
    },
    { name: 'Monaco', country: 'Monaco' },
    { name: 'Monza', country: 'Italy' },
    { name: 'Singapore Marina Bay', country: 'Singapore' },
    { name: 'Spa-Francorchamps', country: 'Belgium' },
    { name: 'Suzuka', country: 'Japan' },
    { name: 'Yas Marina Circuit', country: 'United Arab Emirates' },
  ],
} as const satisfies Record<
  (typeof games)[number],
  Readonly<Array<{ name: string; country: (typeof countries)[number] }>>
>;
