export const countries = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antigua & Barbuda',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia',
  'Bosnia & Herzegovina',
  'Botswana',
  'Brazil',
  'British Virgin Islands',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Cape Verde',
  'Cayman Islands',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Congo',
  'Cook Islands',
  'Costa Rica',
  'Cote D Ivoire',
  'Croatia',
  'Cruise Ship',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Estonia',
  'Ethiopia',
  'Falkland Islands',
  'Faroe Islands',
  'Fiji',
  'Finland',
  'France',
  'French Polynesia',
  'French West Indies',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guam',
  'Guatemala',
  'Guernsey',
  'Guinea',
  'Guinea Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Isle of Man',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jersey',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kuwait',
  'Kyrgyz Republic',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macau',
  'Macedonia',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Namibia',
  'Nepal',
  'Netherlands',
  'Netherlands Antilles',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Norway',
  'Oman',
  'Pakistan',
  'Palestine',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Reunion',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Pierre & Miquelon',
  'Samoa',
  'San Marino',
  'Satellite',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'South Africa',
  'South Korea',
  'Spain',
  'Sri Lanka',
  'St Kitts & Nevis',
  'St Lucia',
  'St Vincent',
  'St. Lucia',
  'Sudan',
  'Suriname',
  'Swaziland',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  "Timor L'Este",
  'Togo',
  'Tonga',
  'Trinidad & Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks & Caicos',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States of America',
  'Uruguay',
  'Uzbekistan',
  'Venezuela',
  'Vietnam',
  'Virgin Islands (US)',
  'Yemen',
  'Zambia',
  'Zimbabwe',
] as const;

export const games = ['Assetto Corsa Competizione', 'F1 23'] as const;

export const eventTypes = ['single', 'championship'] as const;

export const cars = {
  'Assetto Corsa Competizione': [
    { name: 'Aston Martin V12', type: 'GT3' },
    { name: 'Aston Martin V8', type: 'GT3' },
    { name: 'Audi R8 LMS', type: 'GT3' },
    { name: 'Audi R8 LMS EVO', type: 'GT3' },
    { name: 'Audi R8 LMS EVO II', type: 'GT3' },
    { name: 'Bentley Continental 2015', type: 'GT3' },
    { name: 'Bentley Continental 2018', type: 'GT3' },
    { name: 'BMW M6', type: 'GT3' },
    { name: 'BMW M4', type: 'GT3' },
    { name: 'Jaguar G3', type: 'GT3' },
    { name: 'Ferrari 296', type: 'GT3' },
    { name: 'Ferrari 488', type: 'GT3' },
    { name: 'Ferrari 488 EVO', type: 'GT3' },
    { name: 'Honda NSX', type: 'GT3' },
    { name: 'Honda NSX Evo', type: 'GT3' },
    { name: 'Lamborghini Huracán', type: 'GT3' },
    { name: 'Lamborghini Huracán Evo', type: 'GT3' },
    { name: 'Lamborghini Huracán Evo2', type: 'GT3' },
    { name: 'Lexus RC F', type: 'GT3' },
    { name: 'McLaren 650S', type: 'GT3' },
    { name: 'McLaren 720S', type: 'GT3' },
    { name: 'McLaren 720S Evo', type: 'GT3' },
    { name: 'Mercedes AMG', type: 'GT3' },
    { name: 'Mercedes AMG EVO', type: 'GT3' },
    { name: 'Nissan GTR NISMO 2015', type: 'GT3' },
    { name: 'Nissan GTR NISMO 2018', type: 'GT3' },
    { name: 'Porsche 911 GT3R', type: 'GT3' },
    { name: 'Porsche 911 II GT3R', type: 'GT3' },
    { name: 'Porsche 911 GT3 R (992)', type: 'GT3' },
    { name: 'Reiter Engineering R-EX', type: 'GT3' },
    { name: 'Alpine A110 GT4', type: 'GT4' },
    { name: 'AMR V8 VANTAGE GT4', type: 'GT4' },
    { name: 'Audi R8 LMS GT4', type: 'GT4' },
    { name: 'BMW M4 GT4', type: 'GT4' },
    { name: 'Chevrolet Camaro R GT4', type: 'GT4' },
    { name: 'Ginetta G55 GT4', type: 'GT4' },
    { name: 'KTM X-BOW GT4', type: 'GT4' },
    { name: 'Maserati Granturismo MC GT4', type: 'GT4' },
    { name: 'McLaren 570S GT4', type: 'GT4' },
    { name: 'Mercedes AMG GT4', type: 'GT4' },
    { name: 'Porsche 718 Cayman GT4 Clubsport', type: 'GT4' },
    { name: 'Lamborghini Huracán Super Trofeo', type: 'CUP' },
    { name: 'Lamborghini Huracán Super Trofeo EVO2', type: 'CUP' },
    { name: 'Porsche 911 II GT3 Cup', type: 'CUP' },
    { name: 'Porsche 911 GT3 Cup (992)', type: 'CUP' },
    { name: 'Ferrari 488 Challenge Evo', type: 'CUP' },
    { name: 'BMW M2 CS Racing', type: 'TCX' },
  ],
  'F1 23': [],
} as const satisfies Record<
  (typeof games)[number],
  Readonly<Array<{ name: string; type: string }>>
>;
