import { type GetServerSideProps, type NextPage } from 'next';
import { signOut } from 'next-auth/react';
import Head from 'next/head';
import { getServerAuthSession } from '../server/auth';
import { getCalendarPage } from '../lib/dates';

const Home: NextPage = () => {
  console.log(getCalendarPage());

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='min-h-screen w-screen bg-slate-900'>
        <button onClick={() => void signOut()}>Sign out</button>
      </main>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async ctx => {
  const session = await getServerAuthSession(ctx);

  if (!session) {
    return {
      redirect: {
        destination: '/login',
        permanent: false,
      },
    };
  }

  return {
    props: {},
  };
};

export default Home;
