import Calendar from '@calendar/Calendar';
import { type GetServerSideProps, type NextPage } from 'next';
import Head from 'next/head';
import Navbar from '../components/Navbar';
import { getServerAuthSession } from '../server/auth';
import { useCalendarStore } from '../store/useCalendarStore';

const Home: NextPage = () => {
  const { setPage } = useCalendarStore();
  useCalendarStore.subscribe(state => state.monthIndex, setPage);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <main className='grid min-h-[calc(100vh_-_var(--navbar-height))] w-screen grid-cols-1 bg-slate-900 md:grid-cols-[250px_1fr] xl:grid-cols-[250px_1fr_350px]'>
        <Calendar />
      </main>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async ctx => {
  const session = await getServerAuthSession(ctx);

  if (!session) {
    return {
      redirect: {
        destination: '/login',
        permanent: false,
      },
    };
  }

  return {
    props: {
      session,
    },
  };
};

export default Home;
